site:
    title: "徐若薇的博客"
    subtitle: "分享我所得"
    limit: 10
    theme: theme
    lang: zh
    url: "http://blog.xuruowei.com"
    comment: xuruowei
    logo: "-/images/logo.jpg"
    # root: "/blog"
    # link: "{category}/{year}/{month}/{day}/{title}.html"

#MAGIC
authors:
    xrw:
      avatar: -/images/avatars/xrw.jpg
      intro: 人类·将会成为律师🐶？
      name: Xuruowei
#MAGIC

build:
    # output: "public"
    port: 8123
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
